### ISSUE TITLE
Can not process messages encoded with Symfony serializer

### ISSUE THREAD

**Issue by ksaveras** [brefphp/symfony-messenger#24]
```
dcf9e264-9bfe-5b94-b98d-b553c2ade3f0	Invoke Error	
{
    "errorType": "Symfony\\Component\\Messenger\\Exception\\MessageDecodingFailedException",
    "errorMessage": "Encoded envelope should have at least a \"body\" and some \"headers\".",
    "stack": [
        "#0 /var/task/vendor/bref/symfony-messenger/src/Service/Sqs/SqsConsumer.php(38): Symfony\\Component\\Messenger\\Transport\\Serialization\\Serializer->decode()",
        "#1 /var/task/vendor/bref/bref/src/Event/Sqs/SqsHandler.php(18): Bref\\Symfony\\Messenger\\Service\\Sqs\\SqsConsumer->handleSqs()",
        "#2 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(104): Bref\\Event\\Sqs\\SqsHandler->handle()",
        "#3 /opt/bref/bootstrap.php(38): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#4 {main}"
    ]
}
```
Reason is that `SqsConsumer` does not provide header data from SQS message attributes.
`\Bref\Symfony\Messenger\Service\Sqs\SqsConsumer::handleSqs`

**Comment by mnapoli** [comment]
Thanks for the report.

Would your problem be fixed by customizing the serializer on the transport and the consumer, as explained here: https://github.com/brefphp/symfony-messenger#customizing-the-serializer?

**Comment by Nyholm** [comment]
Yes, and no. We could also update the consumers. I'll send a PR.

**Comment by Nyholm** [comment]
@ksaveras See #27 
Will that fix your issue?
